os: osx
language: node_js
node_js: "8"
git:
  depth: 3

env:
  global:
    - ELECTRON_CACHE=$HOME/caches/electron
    - ELECTRON_BUILDER_CACHE=$HOME/caches/electron-builder

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.gradle
    - $HOME/caches

before_deploy:
  - git clone https://github.com/CAU-Kiel-Tech-Inf/socha --depth 1 && cd socha && ./gradlew :server:deploy -q && cd .. && cp -r socha/server/build/runnable server
  - yarn dist-all

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
    - dist/*.AppImage
    - dist/*.exe
    - dist/*.zip
  skip_cleanup: true
  on:
    tags: true