os: osx
osx_image: xcode9.3
language: java
git:
  depth: 3

env:
  global:
    - NODE_VERSION=8
    - ELECTRON_CACHE=$HOME/caches/electron
    - ELECTRON_BUILDER_CACHE=$HOME/caches/electron-builder
    - GIT_TAG=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' package.json)

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.gradle
    - $HOME/caches

install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g yarn

script:
  - yarn

before_deploy:
  - yarn compile-server
  - if git tag $GIT_TAG -a -m "Using git-tag: $GIT_TAG" 2>/dev/null; then
    git tag $GIT_TAG -a -m "Travis generated git-tag"
    git push origin master && git push origin master --tags
    ls -aR
    else echo Tag already exists!; fi
  - yarn release

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
    - dist/*.AppImage
    - dist/*.exe
    - dist/*.zip
    - dist/latest*.yml
  skip_cleanup: true
  on:
    tag: false
    repo: CAU-Kiel-Tech-Inf/socha-gui
    branch: master
