os: osx
language: java
jdk:
  - oraclejdk8
git:
  depth: 3

env:
  global:
    - NODE_VERSION=8
    - ELECTRON_CACHE=$HOME/caches/electron
    - ELECTRON_BUILDER_CACHE=$HOME/caches/electron-builder

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.gradle
    - $HOME/caches

install:
  - nvm install $NODE_VERSION
  - npm install -g yarn

script:
  - nvm use $NODE_VERSION
  - yarn

before_deploy:
  - yarn getserver-https
  - yarn dist-all

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
    - dist/*.AppImage
    - dist/*.exe
    - dist/*.zip
  skip_cleanup: true
  on:
    tags: true
