os: osx
osx_image: xcode9.3
language: java
git:
  depth: 3

env:
  global:
    - NODE_VERSION=12
    - ELECTRON_CACHE=$HOME/caches/electron
    - ELECTRON_BUILDER_CACHE=$HOME/caches/electron-builder

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.gradle
    - $HOME/caches

install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g yarn
  - yarn

script:
  - yarn test

before_deploy:
  - yarn compile-server
  - yarn dist-all

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
    - dist/*.AppImage
    - dist/*.exe
    - dist/*.dmg
    - dist/latest*.yml
  skip_cleanup: true
  on:
    tags: true
